services:
  - type: web
    name: my-django-app
    env: python
    plan: free  # or starter, standard, etc.
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn projectname.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-django-db
          property: connectionString

databases:
  - name: my-django-db
    plan: free  # or starter, standard, etc.
